# Codecov Configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        if_ci_failed: error
        # Post success if no base report exists (new repo/branch)
        if_not_found: success
        # Post success if no coverage uploads (docs-only PRs skip build)
        if_no_uploads: success
    patch:
      default:
        target: 90%
        threshold: 2%
        if_not_found: success
        # Post success if no coverage uploads (docs-only PRs skip build)
        if_no_uploads: success

# Only track coverage for source code files
paths:
  - "src/**"
  - "tests/**"

# Explicitly enable GitHub Checks (default, but being explicit)
github_checks: true

comment:
  layout: "header, diff, flags, components, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

# Ignore generated/third-party code
ignore:
  - "**/*.g.cs"
  - "**/obj/**"
