title: "[Idea] "
labels: ["enhancement", "idea"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea! We love hearing from the community about how to improve DraftSpec.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this idea solve?
      placeholder: |
        Currently, when I try to...
        It's difficult to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: |
        I'd like to be able to...
        The ideal behavior would be...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any workarounds or alternative approaches?
      placeholder: |
        I've thought about...
        Another option might be...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, examples, or screenshots?
      placeholder: Add any other context about the idea here...
