# DraftSpec Full Test Suite
#
# Comprehensive test workflow with validation, full test execution,
# and multiple output formats. Designed for main branch and nightly runs.
#
# Usage: Copy to .github/workflows/full-suite.yml
#
# Features:
# - Pre-flight validation (fail fast)
# - Full spec execution with bail option
# - Multiple output formats (JSON, Markdown)
# - Test result artifacts
# - GitHub job summary

name: Full Test Suite

on:
  push:
    branches: [main]
  schedule:
    # Nightly at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      bail:
        description: 'Stop on first failure'
        required: false
        default: 'false'
        type: boolean

env:
  DOTNET_VERSION: '10.0.x'
  DRAFTSPEC_CLI: DraftSpec.Cli

jobs:
  # Pre-flight validation - fast structural check
  validate:
    name: Validate Specs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install DraftSpec CLI
        run: dotnet tool install -g ${{ env.DRAFTSPEC_CLI }} --prerelease

      - name: Validate spec structure
        run: |
          echo "## Spec Validation" >> $GITHUB_STEP_SUMMARY
          draftspec validate --static --strict
          echo "All specs validated successfully" >> $GITHUB_STEP_SUMMARY

  # Full test execution
  test:
    name: Run All Specs
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install DraftSpec CLI
        run: dotnet tool install -g ${{ env.DRAFTSPEC_CLI }} --prerelease

      - name: Show spec statistics
        run: |
          echo "## Spec Discovery" >> $GITHUB_STEP_SUMMARY
          draftspec list --format tree >> $GITHUB_STEP_SUMMARY || true

      - name: Run all specs
        id: test
        run: |
          BAIL_FLAG=""
          if [ "${{ inputs.bail }}" == "true" ]; then
            BAIL_FLAG="--bail"
          fi

          # Run with JSON output for artifacts
          draftspec run . $BAIL_FLAG --format json -o results.json

          # Also generate markdown for summary
          draftspec run . $BAIL_FLAG --format markdown -o results.md || true

      - name: Generate summary
        if: always()
        run: |
          echo "## Test Results" >> $GITHUB_STEP_SUMMARY
          if [ -f results.md ]; then
            cat results.md >> $GITHUB_STEP_SUMMARY
          elif [ -f results.json ]; then
            PASSED=$(jq '.summary.passed // 0' results.json)
            FAILED=$(jq '.summary.failed // 0' results.json)
            PENDING=$(jq '.summary.pending // 0' results.json)
            DURATION=$(jq '.summary.durationMs // 0' results.json)

            echo "" >> $GITHUB_STEP_SUMMARY
            echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
            echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
            echo "| Passed | $PASSED |" >> $GITHUB_STEP_SUMMARY
            echo "| Failed | $FAILED |" >> $GITHUB_STEP_SUMMARY
            echo "| Pending | $PENDING |" >> $GITHUB_STEP_SUMMARY
            echo "| Duration | ${DURATION}ms |" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload JSON results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-json
          path: results.json
          if-no-files-found: ignore

      - name: Upload Markdown results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-markdown
          path: results.md
          if-no-files-found: ignore

  # Notify on nightly failures (optional)
  notify:
    name: Notify on Failure
    needs: test
    if: failure() && github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Create issue on failure
        uses: actions/github-script@v7
        with:
          script: |
            const title = `Nightly test failure - ${new Date().toISOString().split('T')[0]}`;
            const body = `The nightly test run failed. [View the workflow run](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`;

            // Check if issue already exists
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'nightly-failure'
            });

            if (issues.data.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['nightly-failure', 'bug']
              });
            }
